eFlexPwm: eFlex::Timer
eFlex::Timer
PWM Module.
#include <eFlexPwmTimer.h>
Public Member Functions
Timer (uint8_t index)
Construct a new Timer Module.
bool begin (bool doStart=true, bool doSync=true)
void setDutyCyclePercent (uint8_t dutyCyclePercent)
void setLevel (pwm_level_select_t level)
void setDeadtime (uint16_t deadtimeValue)
void setEnable (bool activate=true)
void setFaultState (pwm_fault_state_t faultState)
void enable (bool value=true)
Enable or disable all instantiated submodules of the timer.
void disable ()
Disable all instantiated submodules of the timer.
bool isEnabled () const
Returns true if the timer is enabled.
uint32_t srcClockHz () const
PWM main counter clock in Hz.
void start (uint8_t subModulesToStart)
Starts the PWM counter for a single or multiple submodules.
void start ()
Starts the PWM counter for all instantiated submodules for this timer.
void stop (uint8_t subModulesToStop)
Stops the PWM counter for a single or multiple submodules.
void stop ()
Stops the PWM counter for all instantiated submodules for this timer.
void setPwmLdok (uint8_t subModulesToUpdate, bool value)
Sets or clears the PWM LDOK bit on a single or multiple submodules.
void setPwmLdok (bool value=true)
Sets or clears the PWM LDOK bit on all instantiated submodules for this timer.
void setupFaultInputFilter (const pwm_fault_input_filter_param_t *faultInputFilterParams)
Sets up the PWM fault input filter.
void setupFaults (pwm_fault_input_t faultNum, const pwm_fault_param_t *faultParams)
Sets up the PWM fault protection.
uint8_t index () const
void dumpRegs (Stream &out=Serial) const
void dumpAllRegs (Stream &out=Serial) const
Detailed Description
PWM Module.
Definition at line 18 of file eFlexPwmTimer.h.
Constructor & Destructor Documentation
Timer()
eFlex::Timer::Timer (uint8_t index)
Construct a new Timer Module.
Parameters
index
Member Function Documentation
begin()
bool eFlex::Timer::begin (bool doStart = true, bool doSync = true)
Parameters
doStart starts signal generation
doSync synchronizes the operation by surrounding it with setPwmLdok (false) / setPwmLdok (true)
Returns
true
false
disable()
void eFlex::Timer::disable () inline
Disable all instantiated submodules of the timer.
This function allows you to disable the output pins without changing anything in the configuration. When the submodule is disabled, its output pins are forced to zero.
Definition at line 62 of file eFlexPwmTimer.h.
References enable().
enable()
void eFlex::Timer::enable (bool value = true)
Enable or disable all instantiated submodules of the timer.
This function allows you to enable/disable the output pins without changing anything in the configuration. When the timer is disabled, its output pins are forced to zero.
Parameters
value true to enable, false otherwise
Referenced by disable().
index()
uint8_t eFlex::Timer::index () const inline
Returns
uint8_t
Definition at line 176 of file eFlexPwmTimer.h.
setPwmLdok() [1/2]
void eFlex::Timer::setPwmLdok (bool value = true) inline
Sets or clears the PWM LDOK bit on all instantiated submodules for this timer.
Note
This operation is not useful if begin() was called with doSync=true
Parameters
value true: Set LDOK bit for the submodule list; false: Clear LDOK bit
Definition at line 145 of file eFlexPwmTimer.h.
References setPwmLdok().
setPwmLdok() [2/2]
void eFlex::Timer::setPwmLdok (uint8_t subModulesToUpdate, bool value) inline
Sets or clears the PWM LDOK bit on a single or multiple submodules.
Set LDOK bit to load buffered values into CTRL[PRSC] and the INIT, FRACVAL and VAL registers. The values are loaded immediately if kPWM_ReloadImmediate option was choosen during config. Else the values are loaded at the next PWM reload point. This function can issue the load command to multiple submodules at the same time.
Parameters
subModulesToUpdate PWM submodules to update with buffered values. This is a logical OR of members of the enumeration pwm_module_control_t
value true: Set LDOK bit for the submodule list; false: Clear LDOK bit
Definition at line 134 of file eFlexPwmTimer.h.
Referenced by setPwmLdok().
setupFaultInputFilter()
void eFlex::Timer::setupFaultInputFilter (const pwm_fault_input_filter_param_t * faultInputFilterParams) inline
Sets up the PWM fault input filter.
Parameters
faultInputFilterParams Parameters passed in to set up the fault input filter.
Definition at line 155 of file eFlexPwmTimer.h.
setupFaults()
void eFlex::Timer::setupFaults (pwm_fault_input_t faultNum, const pwm_fault_param_t * faultParams) inline
Sets up the PWM fault protection.
PWM has 4 fault inputs.
Parameters
faultNum PWM fault to configure.
faultParams Pointer to the PWM fault config structure
Definition at line 167 of file eFlexPwmTimer.h.
start() [1/2]
void eFlex::Timer::start () inline
Starts the PWM counter for all instantiated submodules for this timer.
Note
This operation is not useful if begin() was called with doStart=true
Definition at line 98 of file eFlexPwmTimer.h.
start() [2/2]
void eFlex::Timer::start (uint8_t subModulesToStart) inline
Starts the PWM counter for a single or multiple submodules.
Sets the Run bit which enables the clocks to the PWM submodule. This function can start multiple submodules at the same time.
Parameters
subModulesToStart PWM submodules to start. This is a logical OR of members of the enumeration pwm_module_control_t
Definition at line 89 of file eFlexPwmTimer.h.
stop()
void eFlex::Timer::stop (uint8_t subModulesToStop) inline
Stops the PWM counter for a single or multiple submodules.
Clears the Run bit which resets the submodule's counter. This function can stop multiple submodules at the same time.
Parameters
subModulesToStop PWM submodules to stop. This is a logical OR of members of the enumeration pwm_module_control_t
Definition at line 111 of file eFlexPwmTimer.h.